language: haxe

os:
  - linux

dist: trusty

haxe:
  - "3.4.7"
  - development # the latest build of the development branch in http://build.haxe.org/

matrix:
  allow_failures:
    - haxe: development

install:
  - haxelib git sage-agi https://github.com/sgalland/sage-agi.git
  - haxelib install hxcpp
  - haxelib install hxcpp-debug-server

script:
  - haxe build.hxml
